# Generated by Django 4.0 on 2023-11-21 12:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sport', 'Sport'), ('SUV', 'SUV'), ('Mini Van', 'Mini Van'), ('Classic', 'Classic'), ('Royal', 'Royal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT', 'CVT')], max_length=50),
        ),
    ]
